/** Central path and shell configuration for SPIRION Next island — never hardcode URLs in call sites. */

export const paths = {
  railInsetRem: 1,
  railGapRem: 4,
  railWidthRem: 4.25,
  mainGutterRem: 2.5,
  railDockEdge: 'left' as const,
  railDockStorageKey: 'spirion.v1.railDock',
  brandCornerRadiusPx: 32,
  /** User-facing product name (Plexon sibling to CHECKION / AUDION / BRANDION). */
  brandLabel: 'SPIRION',
  /** Plexon Collection capability id (lowercase, matches sibling product ids). */
  productId: 'spirion' as const,
  /** Legacy capability id — keep until Plexon catalog migrates bindings. */
  legacyProductId: 'dig' as const,
  devPort: 3010,
  defaultDisplayName: 'SPIRION',
  displayNameStorageKey: 'spirion.v1.displayName',
  themeStorageKey: 'spirion.v1.theme',
  localeStorageKey: 'spirion.v1.locale',
  /** Keep in sync with knowledge/paths.json islandChunkReload. */
  chunkReloadStorageKey: 'spirion.v1.chunkReload',
  chunkReloadMaxAttempts: 2,
  defaultTheme: 'msqdx-dark' as const,
  defaultLocale: 'en' as const,
  themeChoices: ['msqdx', 'msqdx-dark', 'msqdx-v2', 'msqdx-v2-dark'] as const,
  localeChoices: ['en', 'de'] as const,
  federationContract: '2026-05-plexon-federation-v3' as const,
  federationMode: 'dummy' as const,
  authDevFallbackSecret: 'spirion-local-dev-auth-secret-min-32-chars!!',
  envPlexonBase: 'NEXT_PLEXON_BASE_URL',
  envPlexonPublicUrl: 'NEXT_PUBLIC_PLEXON_URL',
  /** Env names kept as DIG_* for Coolify/ops continuity (see knowledge/spirion-rename.md). */
  envDigPublicUrl: 'NEXT_PUBLIC_DIG_URL',
  envDigApiUrl: 'DIG_API_URL',
  envPlexonServiceSecret: 'PLEXON_SERVICE_SECRET',
  envDigApiToken: 'DIG_API_TOKEN',
  envPlexonAuthUrl: 'PLEXON_AUTH_URL',
  envPlexonRegisterUrl: 'NEXT_PUBLIC_PLEXON_REGISTER_URL',
  envAuthSecret: 'AUTH_SECRET',
  envFederationMode: 'DIG_FEDERATION_MODE',
  pathAssistantEmbed: '/assistant/embed',
  pathAssistantExpand: '/assistant',
  /** Browser calls go through Next proxy → capture/library Node API. */
  digProxyBase: '/api/dig',
  digApiJobs: '/api/jobs',
  digApiLibrary: '/api/library',
  digApiLibraryFlows: '/api/library/flows',
  digApiLibraryPageFlows: '/api/library/page-flows',
  digApiLibraryReferences: '/api/library/references',
  digApiEnrichment: '/api/enrichment',
  digApiPinterest: '/api/pinterest',
  libraryModes: ['screens', 'devices', 'sections', 'flows'] as const,
  libraryCopy: {
    contentsLabel: 'Contents',
    libraryModeAria: 'Library mode',
    screensLabel: 'Screens',
    sectionsLabel: 'Modules',
    flowsLabel: 'Flows',
    devicesLabel: 'Devices',
    devicesTitle: 'Tablet & mobile',
    devicesHint:
      'Same captures as the desktop gallery, filtered to tablet and mobile. Choose a viewport or show both.',
    devicesAll: 'All',
    devicesTablet: 'Tablet',
    devicesMobile: 'Mobile',
    devicesEmpty: 'No tablet or mobile screens indexed yet.',
    devicesOpen: 'Open tablet & mobile',
    devicesBack: 'Back to desktop gallery',
    pinterestTitle: 'Pinterest boards',
    pinterestHint:
      'Connect a Pinterest app with boards:read and pins:read, then import a board you own. Pins become desktop Library screens and run the same verify → index → enrichment pipeline.',
    pinterestConnect: 'Connect Pinterest',
    pinterestConnected: 'Connected',
    pinterestNotConfigured: 'Pinterest OAuth is not configured on dig-api yet.',
    pinterestImport: 'Import board',
    pinterestImporting: 'Queuing pins…',
    pinterestEmptyBoards: 'No boards on this account.',
    uploadTitle: 'Bulk image upload',
    uploadHint:
      'Drop moodboard stills while Pinterest access is pending. Each JPEG, PNG, WebP, or GIF becomes a desktop Library screen and runs verify → index → enrichment, independently of URL captures.',
    uploadButton: 'Queue images',
    uploadQueuing: 'Queuing images…',
    uploadEmpty: 'Choose one or more images first.',
    pageNarrativeLabel: 'Page narrative',
    flowsSupport: 'Multi-screen design journeys indexed from captures',
    screenDetailBack: 'Back to screens',
    shellBack: 'Back',
    screenDetailSettled: 'Viewport',
    screenDetailFullPage: 'Full page',
    screenDetailOverlay: 'Section overlay',
    screenDetailSections: 'Section look',
    screenDetailSplit: 'Resize screenshot and section look',
    screenInsightTitle: 'Design profile',
    screenInsightKicker: 'Style, layout, and look',
    screenMagazineLabel: 'Design brief',
    screenInsightPageType: 'Page type',
    screenInsightIndustry: 'Industry',
    screenInsightStyle: 'Design style',
    screenInsightLayout: 'Layout',
    screenInsightColor: 'Color',
    screenInsightTypography: 'Typography',
    screenInsightAboveFold: 'Above the fold',
    screenInsightLook: 'Look contract',
    screenInsightPageArc: 'Page arc',
    screenInsightCta: 'CTA',
    screenInsightDensity: 'Density',
    screenInsightRadius: 'Radius',
    screenInsightAvoid: 'Avoid',
    screenInsightSections: 'Sections',
    screenInsightSummary: 'Summary',
    screenInsightCraft: 'Visual craft',
    screenInsightCraftKicker: 'Type, image, space, and chrome',
    screenInsightTypeImage: 'Type and image',
    screenInsightTypeCraft: 'Typography',
    screenInsightImagery: 'Imagery',
    screenInsightSpace: 'Space',
    screenInsightChrome: 'Chrome vs content',
    screenInsightRebuildSpec: 'Rebuild spec',
    screenInsightUx: 'UX assessment',
    screenInsightUxKicker: 'Job, flow, strengths, and risks',
    screenInsightUxJob: 'Above-the-fold job',
    screenInsightUxFlow: 'UX flow',
    screenInsightUxSpacing: 'Spacing and alignment',
    screenInsightUxStrengths: 'UX strengths',
    screenInsightUxRisks: 'UX risks',
    screenInsightFunctionality: 'Functionality',
    screenInsightFunctionalityKicker: 'Detected jobs and UI',
    screenInsightFunctionalityItem: 'Detected UI',
    screenInsightFunctionalityPattern: 'Screen patterns',
    screenInsightFunctionalityModules: 'Notable modules',
    screenInsightSectionSpec: 'Section spec',
    screenInsightSectionSpecKicker: 'Type, image, space, and function',
    screenInsightSectionLook: 'Look',
    screenInsightMore: 'Notes',
    screenInsightPending: 'Design profile appears after enrichment…',
    screenInsightEmpty: 'No design profile signals yet.',
    screenPromptPack: 'Copy prompt pack',
    screenPromptPackCopied: 'Prompt pack copied',
    screenPromptPackFailed: 'Could not copy prompt pack',
    screenPromptPackBrief:
      'Rebuild this captured screen. Obey visual_craft.rebuild_spec and look_contract; do not flatten into a generic card kit.',
    screenFacetStyle: 'Style',
    screenFacetLayout: 'Layout',
    screenFacetIndustry: 'Industry',
    screenFacetAll: 'All',
    screenFacetEmpty: 'No screens match these facets.',
    screenGridHint:
      'Desktop captures only. Filter by style, layout, and industry. Open a card for full-page screenshot, overlay, and look contract.',
    moduleGalleryTitle: 'Modules',
    moduleGalleryHint:
      'Hero, nav, feature, and conversion bands from desktop captures. Body paragraphs stay out of this grid.',
    moduleGalleryEmpty: 'No modules match this filter yet.',
    homeLead: 'Queue health on the meters. Latest screens below, or start a new URL.',
    homeRecentTitle: 'Latest screens',
    homeEmpty: 'No desktop screens indexed yet. Capture a URL to fill the library.',
    queueTitle: 'Queue',
    queueHint:
      'Edit the waiting capture list — skip a URL or move it to the front. Running jobs stay locked. Enrichment is a second lane.',
    queueEmpty: 'Nothing waiting in the capture queue.',
    queueSkip: 'Skip',
    queueFront: 'Run next',
    queueMoveUp: 'Earlier',
    queueMoveDown: 'Later',
    queueCaptureLane: 'Capture',
    queueEnrichLane: 'Enrichment',
    queueOpen: 'Open queue',
    queueLive: 'Now running',
    queueWaiting: 'Waiting',
    queueFailed: 'Failed',
    queueComplete: 'Complete',
    queueSlots: 'Capture slots',
    queueHealth: 'Pipeline health',
    queueEditsNeedApi: 'Skip and reorder need a dig-api deploy. That restart would drop the live in-memory queue.',
    dashboardCapture: 'Capture queue',
    dashboardEnrich: 'Enrichment',
    dashboardLive: 'Live',
    analysesHint: 'Indexed design summaries. Open a card to read the screen in Library — not a second ontology dump.',
    analysesEmpty: 'No analyses yet.',
    analysesOpen: 'Open in Library',
    enrichmentHint: 'Live enrichment queue. Active jobs first; open a capture in Library when it has a screen.',
    enrichmentEmpty: 'No enrichment jobs.',
    flowsGalleryHint: 'Multi-screen journeys. Open a card to walk the captured screens.',
    flowsEmpty: 'No flows indexed yet.',
  },
  /** Keep in sync with knowledge/paths.json libraryScreenGallery. */
  libraryScreenGallery: {
    primaryViewport: 'desktop',
    deviceViewports: ['tablet', 'mobile'] as const,
    devicesQueryParam: 'viewport',
    devicesAllValue: 'all',
  },
  /** Keep in sync with knowledge/paths.json libraryScreenDetail. */
  libraryScreenDetail: {
    splitStorageKey: 'spirion.v1.screenDetailSplit',
    sideRatioDefault: 0.32,
    sideRatioMin: 0.2,
    sideRatioMax: 0.58,
  },
  /** Keep in sync with knowledge/paths.json libraryModuleGallery. */
  libraryModuleGallery: {
    queryParam: 'module',
    allValue: 'all',
    categories: ['hero', 'nav', 'feature', 'conversion', 'commerce', 'social_proof'] as const,
    thinCategories: ['content'] as const,
    thinSignatures: ['body', 'unknown'] as const,
    maxPerCategory: 12,
    maxFiltered: 40,
    cardAspect: 1.7778,
  },
  /** Keep in sync with knowledge/paths.json islandSurfaces. */
  islandSurfaces: {
    homeRecentCount: 8,
    enrichmentListCap: 12,
    analysesListCap: 24,
    queuePollMs: 10000,
    homeLiveOpsCap: 6,
    queueEditHeadCap: 40,
  },
  captureJobs: {
    maxConcurrent: 6,
  },
  pinterest: {
    islandCallbackPath: '/api/pinterest/callback',
    statusPath: '/status',
    oauthStartPath: '/oauth/start',
    boardsPath: '/boards',
    importPath: '/import',
    privacyPath: '/privacy',
    website: 'https://spirion.projects-a.plygrnd.tech',
    submissionDoc: 'knowledge/pinterest-app-submission.md',
  },
  imageIngest: {
    imagesPath: '/images',
    fieldName: 'files',
    accept: 'image/jpeg,image/png,image/webp,image/gif',
    maxFiles: 40,
  },
  apiPlatformProvisioningProjects: '/api/platform/provisioning/projects',
  platformProjectQueryParam: 'platformProjectId',
  /** Query keys for GET /api/library/screens facet filters — keep in sync with knowledge/paths.json libraryScreenFacets. */
  libraryFacetQuery: {
    style: 'style',
    layout: 'layout',
    industry: 'industry',
  },
  /** Keep in sync with knowledge/paths.json libraryScreenFacets.pollMs */
  libraryScreensPollMs: 15_000,
  defaultDigApiUrl: 'http://127.0.0.1:8787',
  msqdxUiSibling: '../../../msqdx-ui',
  bindingTicket: 'knowledge/plexon-dig-binding-ticket.md',
  renameDoc: 'knowledge/spirion-rename.md',
  platformDoc: 'docs/DIG-013-plexon-app.md',
  routes: {
    home: '/',
    login: '/login',
    projects: '/projects',
    capture: '/capture',
    library: '/library',
    enrichment: '/enrichment',
    queue: '/queue',
    analyses: '/analyses',
    settings: '/settings',
    rebuild: '/rebuild',
    rebuildNorthline: '/rebuild/northline',
    privacy: '/privacy',
    apiAuthNextAuth: '/api/auth',
    apiHealth: '/api/health',
  },
  /** Luxury-auto rebuild mock from capture brief (not production marketing). */
  rebuildDemo: {
    brand: 'Porsche',
    headline: 'Flachbau RS.',
    support:
      'Cinematic full-bleed hero, dark scrim, one clear action — rebuilt from measured SPIRION evidence.',
    primaryCta: 'Alle anzeigen',
    secondaryCta: 'Konfigurieren',
    heroImage: '/rebuild/hero-night-car.png',
    briefPath: 'knowledge/porsche-germany-rebuild-brief.md',
    captureRunId: 'cap_3f48fbb23e074fd6ae68540760f01b92',
  },
  /** Insurance homepage composed from City Arcade craft via SPIRION MCP. */
  northlineRebuild: {
    brand: 'Northline',
    wordmark: 'NORTHLINE',
    kicker: 'Mutual cover, measured.',
    intro:
      'A line of cover written like architecture: few images, large type, nothing decorative in the chrome.',
    valueTitle: 'COVER THAT HOLDS STILL',
    valueLead: 'Life, health, and property as one measured line — not a marketplace of cards.',
    whyTitle: 'WHY NORTHLINE',
    whyBody: 'We underwrite slowly. Claims move fast. The page should feel the same way.',
    conversionLine1: 'Ask for a line.',
    conversionLine2: 'Not a bundle.',
    primaryCta: 'Request a line',
    secondaryCta: 'Read the cover',
    heroImage: '/rebuild/northline-architecture.png',
    briefPath: 'knowledge/northline-insurance-rebuild.md',
    captureRunId: 'cap_42a3ef1cc922444b8ab0c6148df0a93f',
    viewportCaptureId: 'vpc_97ce4ecf8a204c4ab4e0fedda6073623',
    nav: ['Cover', 'Life', 'Health', 'Claims'],
    stats: [
      { value: '48h', label: 'First claim note' },
      { value: '12', label: 'Countries on one line' },
      { value: '1:1', label: 'Named underwriter' },
    ],
    features: [
      { title: 'Named lines', body: 'Every policy has an underwriter you can write to.' },
      { title: 'Quiet chrome', body: 'No marketplace grid. Cover, terms, a single action.' },
      { title: 'Still imagery', body: 'One building, reused in grayscale. Nothing extra.' },
      { title: 'Outline only', body: 'Buttons stay hollow. Accent lives in the last band.' },
    ],
  },
} as const

/** Append Collection query to island routes so nav keeps platformProjectId. */
export function withPlatformProject(
  href: string,
  platformProjectId: string | null | undefined,
): string {
  const id = platformProjectId?.trim()
  if (!id) return href
  const url = new URL(href, 'http://spirion.local')
  url.searchParams.set(paths.platformProjectQueryParam, id)
  return `${url.pathname}${url.search}`
}
