#!/usr/bin/env python3
"""Build knowledge/catalogs/insurance-1000.json from curated majors + Wikidata snapshot."""
from __future__ import annotations

import json
import re
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "knowledge" / "catalogs" / "insurance-1000.json"
SOURCE = ROOT / "knowledge" / "catalogs" / "sources" / "insurance-wikidata-2026.json"
EXISTING = [
    ROOT / "knowledge" / "catalogs" / "automotive-oem-50.json",
    ROOT / "knowledge" / "catalogs" / "cross-industry-100.json",
    ROOT / "knowledge" / "catalogs" / "engineering-manufacturing-1000.json",
]


def host_key(url: str) -> str:
    raw = url.strip()
    parsed = urlparse(raw if "://" in raw else f"https://{raw}")
    host = (parsed.hostname or "").lower().removeprefix("www.")
    path = parsed.path or "/"
    if len(path) > 1 and path.endswith("/"):
        path = path[:-1]
    return host if path == "/" else f"{host}{path}"


def slug(name: str) -> str:
    out: list[str] = []
    for ch in name.lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in " &._/'":
            if out and out[-1] != "-":
                out.append("-")
    return "".join(out).strip("-")


COUNTRY_ISO = {
    "united states": "US",
    "united states of america": "US",
    "usa": "US",
    "united kingdom": "GB",
    "great britain": "GB",
    "england": "GB",
    "germany": "DE",
    "france": "FR",
    "italy": "IT",
    "spain": "ES",
    "switzerland": "CH",
    "netherlands": "NL",
    "belgium": "BE",
    "austria": "AT",
    "sweden": "SE",
    "norway": "NO",
    "denmark": "DK",
    "finland": "FI",
    "ireland": "IE",
    "portugal": "PT",
    "poland": "PL",
    "czech republic": "CZ",
    "czechia": "CZ",
    "slovakia": "SK",
    "hungary": "HU",
    "romania": "RO",
    "bulgaria": "BG",
    "greece": "GR",
    "turkey": "TR",
    "türkiye": "TR",
    "russia": "RU",
    "ukraine": "UA",
    "canada": "CA",
    "mexico": "MX",
    "brazil": "BR",
    "argentina": "AR",
    "chile": "CL",
    "colombia": "CO",
    "peru": "PE",
    "japan": "JP",
    "china": "CN",
    "people's republic of china": "CN",
    "hong kong": "HK",
    "taiwan": "TW",
    "south korea": "KR",
    "korea": "KR",
    "india": "IN",
    "indonesia": "ID",
    "dutch east indies": "ID",
    "malaysia": "MY",
    "singapore": "SG",
    "thailand": "TH",
    "vietnam": "VN",
    "philippines": "PH",
    "australia": "AU",
    "new zealand": "NZ",
    "south africa": "ZA",
    "nigeria": "NG",
    "kenya": "KE",
    "egypt": "EG",
    "morocco": "MA",
    "israel": "IL",
    "saudi arabia": "SA",
    "united arab emirates": "AE",
    "qatar": "QA",
    "bahrain": "BH",
    "kuwait": "KW",
    "bermuda": "BM",
    "cayman islands": "KY",
    "luxembourg": "LU",
    "liechtenstein": "LI",
    "iceland": "IS",
    "faroe islands": "FO",
    "croatia": "HR",
    "slovenia": "SI",
    "serbia": "RS",
    "bosnia and herzegovina": "BA",
    "north macedonia": "MK",
    "albania": "AL",
    "estonia": "EE",
    "latvia": "LV",
    "lithuania": "LT",
    "bangladesh": "BD",
    "pakistan": "PK",
    "sri lanka": "LK",
    "nepal": "NP",
    "angola": "AO",
    "ghana": "GH",
    "tunisia": "TN",
    "algeria": "DZ",
    "lebanon": "LB",
    "jordan": "JO",
    "oman": "OM",
    "armenia": "AM",
    "azerbaijan": "AZ",
    "georgia": "GE",
    "kazakhstan": "KZ",
    "uzbekistan": "UZ",
    "mongolia": "MN",
    "cambodia": "KH",
    "laos": "LA",
    "myanmar": "MM",
    "brunei": "BN",
    "macau": "MO",
    "puerto rico": "PR",
    "jamaica": "JM",
    "trinidad and tobago": "TT",
    "barbados": "BB",
    "bahamas": "BS",
    "uruguay": "UY",
    "paraguay": "PY",
    "ecuador": "EC",
    "bolivia": "BO",
    "venezuela": "VE",
    "costa rica": "CR",
    "panama": "PA",
    "guatemala": "GT",
    "honduras": "HN",
    "el salvador": "SV",
    "nicaragua": "NI",
    "dominican republic": "DO",
    "cyprus": "CY",
    "malta": "MT",
    "monaco": "MC",
}

TLD_ISO = {
    "com": "US",
    "de": "DE",
    "fr": "FR",
    "it": "IT",
    "es": "ES",
    "ch": "CH",
    "nl": "NL",
    "be": "BE",
    "at": "AT",
    "se": "SE",
    "no": "NO",
    "dk": "DK",
    "fi": "FI",
    "ie": "IE",
    "pt": "PT",
    "pl": "PL",
    "cz": "CZ",
    "sk": "SK",
    "hu": "HU",
    "ro": "RO",
    "bg": "BG",
    "gr": "GR",
    "tr": "TR",
    "ru": "RU",
    "ua": "UA",
    "ca": "CA",
    "mx": "MX",
    "br": "BR",
    "ar": "AR",
    "cl": "CL",
    "jp": "JP",
    "cn": "CN",
    "hk": "HK",
    "tw": "TW",
    "kr": "KR",
    "in": "IN",
    "id": "ID",
    "my": "MY",
    "sg": "SG",
    "th": "TH",
    "vn": "VN",
    "ph": "PH",
    "au": "AU",
    "nz": "NZ",
    "za": "ZA",
    "ng": "NG",
    "il": "IL",
    "sa": "SA",
    "ae": "AE",
    "qa": "QA",
    "bm": "BM",
    "lu": "LU",
    "hr": "HR",
    "si": "SI",
    "rs": "RS",
    "ee": "EE",
    "lv": "LV",
    "lt": "LT",
    "uk": "GB",
    "co.uk": "GB",
    "com.au": "AU",
    "co.jp": "JP",
    "co.kr": "KR",
    "co.in": "IN",
    "com.cn": "CN",
    "com.tr": "TR",
    "co.za": "ZA",
    "com.br": "BR",
    "com.mx": "MX",
    "co.nz": "NZ",
    "com.sg": "SG",
    "com.hk": "HK",
    "com.tw": "TW",
}


def country_iso(country: str, url: str) -> str:
    key = (country or "").strip().lower()
    if key in COUNTRY_ISO:
        return COUNTRY_ISO[key]
    host = (urlparse(url).hostname or "").lower().removeprefix("www.")
    parts = host.split(".")
    for n in (3, 2, 1):
        if len(parts) >= n:
            tld = ".".join(parts[-n:])
            if tld in TLD_ISO:
                return TLD_ISO[tld]
    return "XX"


def infer_group(name: str, url: str) -> str:
    blob = f"{name} {url}".lower()
    rules = [
        ("Reinsurance", ("reinsurance", "munich re", "swiss re", "hannover re", "korean re", "china re", "genre.com", "renre.com", "transre", "partnerre", "scor.com", "lloyds.com")),
        ("Insurance broker", ("broker", "marsh.com", "marshmclennan", "aon.com", "wtwco", "ajg.com", "howden", "lockton", "hubinternational", "bbinsurance", "acrisure", "guycarp")),
        ("Insurtech", ("insurtech", "lemonade.com", "joinroot", "hippo.com", "metromile", "nextinsurance", "wefox", "alan.com", "policybazaar", "acko.com", "godigit", "zhongan", "coalitioninc", "at-bay", "cloverhealth", "hioscar")),
        ("Health insurance", ("health", "humana", "cigna", "anthem", "elevance", "kaiser", "centene", "molina", "bluecross", "blue cross", "blue-cross", "aetna", "highmark", "caresource", "krankenkasse", "bupa", "delta dental")),
        ("Pet insurance", ("pet insurance", "trupanion", "petsbest", "embracepet", "healthypaws", "figopet", "spotpet", "manypets")),
        ("Travel insurance", ("travel insurance", "allianz-travel", "worldnomads", "travelguard")),
        ("Title insurance", ("title insurance", "firstam.com", "fntg.com", "oldrepublictitle", "stewart.com/title")),
        ("Credit / surety", ("credit insurance", "surety", "coface", "eulerhermes", "allianz-trade", "atradius")),
        ("Takaful", ("takaful",)),
        ("Crop / agriculture", ("crop insurance", "agriculture insurance", "fcic")),
        ("Workers compensation", ("workers comp", "workers' compensation", "accident fund")),
        ("Auto insurance", ("auto insurance", "car insurance", "geico", "progressive.com", "thegeneral", "esurance", "safeco")),
        ("Marine / specialty", ("marine insurance", "lloyd", "hiscox", "beazley", "markel")),
        ("Pension / retirement", ("pension", "retirement", "tiaa", "varma", "ilmarinen")),
        ("Mutual / cooperative", ("mutual", "cooperative", "co-operative", "krankenkasse")),
        ("Life insurance", ("life insurance", "life assurance", "annuity", "nippon life", "dai-ichi", "meiji yasuda")),
        ("Property & casualty", ("property", "casualty", "p&c", "home insurance")),
    ]
    for group, needles in rules:
        if any(n in blob for n in needles):
            return group
    return "Composite / multiline"


# Curated 2026 majors — listed first so they win on host collisions.
# name, group, country, url
CURATED: list[tuple[str, str, str, str]] = [
    ("Allianz", "Composite / multiline", "DE", "https://www.allianz.com/"),
    ("AXA", "Composite / multiline", "FR", "https://www.axa.com/"),
    ("Assicurazioni Generali", "Composite / multiline", "IT", "https://www.generali.com/"),
    ("Zurich Insurance Group", "Composite / multiline", "CH", "https://www.zurich.com/"),
    ("American International Group", "Composite / multiline", "US", "https://www.aig.com/"),
    ("Chubb", "Property & casualty", "CH", "https://www.chubb.com/"),
    ("Mapfre", "Composite / multiline", "ES", "https://www.mapfre.com/"),
    ("Talanx", "Composite / multiline", "DE", "https://www.talanx.com/"),
    ("MS&AD Insurance Group", "Composite / multiline", "JP", "https://www.ms-ad-hd.com/"),
    ("Tokio Marine", "Composite / multiline", "JP", "https://www.tokiomarinehd.com/"),
    ("SOMPO Holdings", "Composite / multiline", "JP", "https://www.sompo-hd.com/"),
    ("QBE Insurance", "Property & casualty", "AU", "https://www.qbe.com/"),
    ("Intact Financial", "Property & casualty", "CA", "https://www.intactfc.com/"),
    ("Fairfax Financial", "Property & casualty", "CA", "https://www.fairfax.ca/"),
    ("Sampo", "Composite / multiline", "FI", "https://www.sampo.com/"),
    ("Vienna Insurance Group", "Composite / multiline", "AT", "https://www.vig.com/"),
    ("Uniqa", "Composite / multiline", "AT", "https://www.uniqagroup.com/"),
    ("PZU", "Composite / multiline", "PL", "https://www.pzu.pl/"),
    ("Ageas", "Composite / multiline", "BE", "https://www.ageas.com/"),
    ("NN Group", "Life insurance", "NL", "https://www.nn-group.com/"),
    ("Aegon", "Life insurance", "NL", "https://www.aegon.com/"),
    ("Baloise", "Composite / multiline", "CH", "https://www.baloise.com/"),
    ("Helvetia", "Composite / multiline", "CH", "https://www.helvetia.com/"),
    ("Swiss Life", "Life insurance", "CH", "https://www.swisslife.com/"),
    ("Aviva", "Composite / multiline", "GB", "https://www.aviva.com/"),
    ("Legal & General", "Life insurance", "GB", "https://www.legalandgeneral.com/"),
    ("Prudential plc", "Life insurance", "GB", "https://www.prudentialplc.com/"),
    ("Phoenix Group", "Life insurance", "GB", "https://www.thephoenixgroup.com/"),
    ("RSA Insurance", "Property & casualty", "GB", "https://www.rsagroup.com/"),
    ("Direct Line Group", "Auto insurance", "GB", "https://www.directlinegroup.co.uk/"),
    ("Admiral Group", "Auto insurance", "GB", "https://admiralgroup.co.uk/"),
    ("Old Mutual", "Life insurance", "ZA", "https://www.oldmutual.com/"),
    ("Sanlam", "Life insurance", "ZA", "https://www.sanlam.com/"),
    ("Ping An Insurance", "Composite / multiline", "CN", "https://group.pingan.com/"),
    ("China Life Insurance", "Life insurance", "CN", "https://www.e-chinalife.com/"),
    ("China Pacific Insurance", "Composite / multiline", "CN", "https://www.cpic.com.cn/"),
    ("PICC", "Property & casualty", "CN", "https://property.picc.com/"),
    ("AIA Group", "Life insurance", "HK", "https://www.aia.com/"),
    ("Manulife", "Life insurance", "CA", "https://www.manulife.com/"),
    ("Sun Life", "Life insurance", "CA", "https://www.sunlife.com/"),
    ("Great-West Lifeco", "Life insurance", "CA", "https://www.greatwestlifeco.com/"),
    ("Canada Life", "Life insurance", "CA", "https://www.canadalife.com/"),
    ("IAG", "Property & casualty", "AU", "https://www.iag.com.au/"),
    ("Suncorp", "Property & casualty", "AU", "https://www.suncorp.com.au/"),
    ("Berkshire Hathaway", "Property & casualty", "US", "https://www.berkshirehathaway.com/"),
    ("State Farm", "Property & casualty", "US", "https://www.statefarm.com/"),
    ("Progressive", "Auto insurance", "US", "https://www.progressive.com/"),
    ("Allstate", "Property & casualty", "US", "https://www.allstate.com/"),
    ("GEICO", "Auto insurance", "US", "https://www.geico.com/"),
    ("Liberty Mutual", "Property & casualty", "US", "https://www.libertymutual.com/"),
    ("USAA", "Property & casualty", "US", "https://www.usaa.com/"),
    ("Travelers", "Property & casualty", "US", "https://www.travelers.com/"),
    ("Farmers Insurance", "Property & casualty", "US", "https://www.farmers.com/"),
    ("Nationwide", "Composite / multiline", "US", "https://www.nationwide.com/"),
    ("American Family Insurance", "Property & casualty", "US", "https://www.amfam.com/"),
    ("The Hartford", "Property & casualty", "US", "https://www.thehartford.com/"),
    ("Auto-Owners Insurance", "Property & casualty", "US", "https://www.auto-owners.com/"),
    ("Erie Insurance", "Property & casualty", "US", "https://www.erieinsurance.com/"),
    ("Amica Mutual", "Mutual / cooperative", "US", "https://www.amica.com/"),
    ("CNA Financial", "Property & casualty", "US", "https://www.cna.com/"),
    ("W. R. Berkley", "Property & casualty", "US", "https://www.berkley.com/"),
    ("Markel", "Marine / specialty", "US", "https://www.markel.com/"),
    ("Cincinnati Financial", "Property & casualty", "US", "https://www.cinfin.com/"),
    ("Hanover Insurance", "Property & casualty", "US", "https://www.hanover.com/"),
    ("Selective Insurance", "Property & casualty", "US", "https://www.selective.com/"),
    ("Kemper", "Property & casualty", "US", "https://www.kemper.com/"),
    ("Assurant", "Specialty / credit", "US", "https://www.assurant.com/"),
    ("Mercury Insurance", "Auto insurance", "US", "https://www.mercuryinsurance.com/"),
    ("The General", "Auto insurance", "US", "https://www.thegeneral.com/"),
    ("MetLife", "Life insurance", "US", "https://www.metlife.com/"),
    ("Prudential Financial", "Life insurance", "US", "https://www.prudential.com/"),
    ("New York Life", "Life insurance", "US", "https://www.newyorklife.com/"),
    ("Northwestern Mutual", "Life insurance", "US", "https://www.northwesternmutual.com/"),
    ("MassMutual", "Life insurance", "US", "https://www.massmutual.com/"),
    ("Lincoln Financial", "Life insurance", "US", "https://www.lincolnfinancial.com/"),
    ("Principal Financial", "Pension / retirement", "US", "https://www.principal.com/"),
    ("Pacific Life", "Life insurance", "US", "https://www.pacificlife.com/"),
    ("Guardian Life", "Life insurance", "US", "https://www.guardianlife.com/"),
    ("Mutual of Omaha", "Life insurance", "US", "https://www.mutualofomaha.com/"),
    ("TIAA", "Pension / retirement", "US", "https://www.tiaa.org/"),
    ("Thrivent", "Mutual / cooperative", "US", "https://www.thrivent.com/"),
    ("Aflac", "Life insurance", "US", "https://www.aflac.com/"),
    ("Unum", "Life insurance", "US", "https://www.unum.com/"),
    ("Globe Life", "Life insurance", "US", "https://www.globelifeinsurance.com/"),
    ("Genworth", "Life insurance", "US", "https://www.genworth.com/"),
    ("Primerica", "Life insurance", "US", "https://www.primerica.com/"),
    ("Protective Life", "Life insurance", "US", "https://www.protective.com/"),
    ("Equitable", "Life insurance", "US", "https://equitable.com/"),
    ("Corebridge Financial", "Life insurance", "US", "https://www.corebridgefinancial.com/"),
    ("Brighthouse Financial", "Life insurance", "US", "https://www.brighthousefinancial.com/"),
    ("Voya Financial", "Pension / retirement", "US", "https://www.voya.com/"),
    ("Jackson", "Life insurance", "US", "https://www.jackson.com/"),
    ("Securian", "Life insurance", "US", "https://www.securian.com/"),
    ("Western & Southern", "Life insurance", "US", "https://www.westernsouthern.com/"),
    ("Elevance Health", "Health insurance", "US", "https://www.elevancehealth.com/"),
    ("Humana", "Health insurance", "US", "https://www.humana.com/"),
    ("Cigna", "Health insurance", "US", "https://www.cigna.com/"),
    ("Kaiser Permanente", "Health insurance", "US", "https://www.kaiserpermanente.org/"),
    ("Centene", "Health insurance", "US", "https://www.centene.com/"),
    ("Molina Healthcare", "Health insurance", "US", "https://www.molinahealthcare.com/"),
    ("HCSC", "Health insurance", "US", "https://www.hcsc.com/"),
    ("Highmark", "Health insurance", "US", "https://www.highmark.com/"),
    ("Aetna", "Health insurance", "US", "https://www.aetna.com/"),
    ("Florida Blue", "Health insurance", "US", "https://www.floridablue.com/"),
    ("Blue Shield of California", "Health insurance", "US", "https://www.blueshieldca.com/"),
    ("Premera Blue Cross", "Health insurance", "US", "https://www.premera.com/"),
    ("CareSource", "Health insurance", "US", "https://www.caresource.com/"),
    ("Oscar Health", "Insurtech", "US", "https://www.hioscar.com/"),
    ("Delta Dental", "Health insurance", "US", "https://www.deltadental.com/"),
    ("Munich Re", "Reinsurance", "DE", "https://www.munichre.com/"),
    ("Swiss Re", "Reinsurance", "CH", "https://www.swissre.com/"),
    ("Hannover Re", "Reinsurance", "DE", "https://www.hannover-re.com/"),
    ("SCOR", "Reinsurance", "FR", "https://www.scor.com/"),
    ("Everest Group", "Reinsurance", "BM", "https://www.everestglobal.com/"),
    ("RenaissanceRe", "Reinsurance", "BM", "https://www.renre.com/"),
    ("Arch Capital", "Reinsurance", "BM", "https://www.archgroup.com/"),
    ("Reinsurance Group of America", "Reinsurance", "US", "https://www.rgare.com/"),
    ("China Re", "Reinsurance", "CN", "https://www.chinare.com.cn/"),
    ("Korean Re", "Reinsurance", "KR", "https://www.koreanre.co.kr/"),
    ("GIC Re", "Reinsurance", "IN", "https://www.gicofindia.com/"),
    ("Gen Re", "Reinsurance", "US", "https://www.genre.com/"),
    ("TransRe", "Reinsurance", "US", "https://www.transre.com/"),
    ("Lloyd's of London", "Marine / specialty", "GB", "https://www.lloyds.com/"),
    ("Hiscox", "Marine / specialty", "BM", "https://www.hiscoxgroup.com/"),
    ("Beazley", "Marine / specialty", "GB", "https://www.beazley.com/"),
    ("Axis Capital", "Reinsurance", "BM", "https://www.axiscapital.com/"),
    ("PartnerRe", "Reinsurance", "BM", "https://www.partnerre.com/"),
    ("Marsh", "Insurance broker", "US", "https://www.marsh.com/"),
    ("Marsh McLennan", "Insurance broker", "US", "https://www.marshmclennan.com/"),
    ("Aon", "Insurance broker", "GB", "https://www.aon.com/"),
    ("WTW", "Insurance broker", "GB", "https://www.wtwco.com/"),
    ("Arthur J. Gallagher", "Insurance broker", "US", "https://www.ajg.com/"),
    ("Howden", "Insurance broker", "GB", "https://www.howdengroup.com/"),
    ("Lockton", "Insurance broker", "US", "https://www.lockton.com/"),
    ("Brown & Brown", "Insurance broker", "US", "https://www.bbinsurance.com/"),
    ("Hub International", "Insurance broker", "US", "https://www.hubinternational.com/"),
    ("Acrisure", "Insurance broker", "US", "https://www.acrisure.com/"),
    ("Guy Carpenter", "Insurance broker", "US", "https://www.guycarp.com/"),
    ("Lemonade", "Insurtech", "US", "https://www.lemonade.com/"),
    ("Root Insurance", "Insurtech", "US", "https://www.joinroot.com/"),
    ("Hippo", "Insurtech", "US", "https://www.hippo.com/"),
    ("Next Insurance", "Insurtech", "US", "https://www.nextinsurance.com/"),
    ("Policygenius", "Insurtech", "US", "https://www.policygenius.com/"),
    ("Coalition", "Insurtech", "US", "https://www.coalitioninc.com/"),
    ("At-Bay", "Insurtech", "US", "https://www.at-bay.com/"),
    ("Wefox", "Insurtech", "DE", "https://www.wefox.com/"),
    ("Alan", "Insurtech", "FR", "https://alan.com/"),
    ("ACKO", "Insurtech", "IN", "https://www.acko.com/"),
    ("Go Digit", "Insurtech", "IN", "https://www.godigit.com/"),
    ("ZhongAn", "Insurtech", "CN", "https://www.zhongan.com/"),
    ("Clover Health", "Insurtech", "US", "https://www.cloverhealth.com/"),
    ("Trupanion", "Pet insurance", "US", "https://www.trupanion.com/"),
    ("Healthy Paws", "Pet insurance", "US", "https://www.healthypawspetinsurance.com/"),
    ("Pets Best", "Pet insurance", "US", "https://www.petsbest.com/"),
    ("HUK-Coburg", "Mutual / cooperative", "DE", "https://www.huk.de/"),
    ("Debeka", "Mutual / cooperative", "DE", "https://www.debeka.de/"),
    ("R+V Versicherung", "Mutual / cooperative", "DE", "https://www.ruv.de/"),
    ("Ergo", "Composite / multiline", "DE", "https://www.ergo.com/"),
    ("Gothaer", "Mutual / cooperative", "DE", "https://www.gothaer.de/"),
    ("Signal Iduna", "Mutual / cooperative", "DE", "https://www.signal-iduna.de/"),
    ("HDI", "Property & casualty", "DE", "https://www.hdi.de/"),
    ("DEVK", "Mutual / cooperative", "DE", "https://www.devk.de/"),
    ("Groupama", "Mutual / cooperative", "FR", "https://www.groupama.com/"),
    ("Macif", "Mutual / cooperative", "FR", "https://www.macif.fr/"),
    ("MAIF", "Mutual / cooperative", "FR", "https://www.maif.fr/"),
    ("CNP Assurances", "Life insurance", "FR", "https://www.cnp.fr/"),
    ("Covea", "Mutual / cooperative", "FR", "https://www.covea.eu/"),
    ("Crédit Agricole Assurances", "Bancassurance", "FR", "https://www.ca-assurances.com/"),
    ("BNP Paribas Cardif", "Bancassurance", "FR", "https://www.bnpparibascardif.com/"),
    ("Bupa", "Health insurance", "GB", "https://www.bupa.com/"),
    ("Royal London", "Mutual / cooperative", "GB", "https://www.royallondon.com/"),
    ("LV=", "Mutual / cooperative", "GB", "https://www.lv.com/"),
    ("NFU Mutual", "Mutual / cooperative", "GB", "https://www.nfumutual.co.uk/"),
    ("Vitality", "Health insurance", "GB", "https://www.vitality.co.uk/"),
    ("Nippon Life", "Life insurance", "JP", "https://www.nissay.co.jp/"),
    ("Dai-ichi Life", "Life insurance", "JP", "https://www.dai-ichi-life.co.jp/"),
    ("Meiji Yasuda Life", "Life insurance", "JP", "https://www.meijiyasuda.co.jp/"),
    ("Sumitomo Life", "Life insurance", "JP", "https://www.sumitomolife.co.jp/"),
    ("Japan Post Insurance", "Life insurance", "JP", "https://www.jp-life.japanpost.jp/"),
    ("LIC", "Life insurance", "IN", "https://licindia.in/"),
    ("HDFC Life", "Life insurance", "IN", "https://www.hdfclife.com/"),
    ("SBI Life", "Life insurance", "IN", "https://www.sbilife.co.in/"),
    ("ICICI Prudential Life", "Life insurance", "IN", "https://www.iciciprulife.com/"),
    ("Star Health", "Health insurance", "IN", "https://www.starhealth.in/"),
    ("Policybazaar", "Insurtech", "IN", "https://www.policybazaar.com/"),
    ("Samsung Life", "Life insurance", "KR", "https://www.samsunglife.com/"),
    ("Samsung Fire & Marine", "Property & casualty", "KR", "https://www.samsungfire.com/"),
    ("Hanwha Life", "Life insurance", "KR", "https://www.hanwhalife.com/"),
    ("Kyobo Life", "Life insurance", "KR", "https://www.kyobo.co.kr/"),
    ("Desjardins", "Mutual / cooperative", "CA", "https://www.desjardins.com/"),
    ("Co-operators", "Mutual / cooperative", "CA", "https://www.cooperators.ca/"),
    ("Wawanesa", "Mutual / cooperative", "CA", "https://www.wawanesa.com/"),
    ("Allianz Trade", "Credit / surety", "FR", "https://www.allianz-trade.com/"),
    ("Coface", "Credit / surety", "FR", "https://www.coface.com/"),
    ("Atradius", "Credit / surety", "NL", "https://atradius.com/"),
    ("First American", "Title insurance", "US", "https://www.firstam.com/"),
    ("Fidelity National Financial", "Title insurance", "US", "https://www.fnf.com/"),
    ("Old Republic Title", "Title insurance", "US", "https://www.oldrepublictitle.com/"),
    ("World Nomads", "Travel insurance", "AU", "https://www.worldnomads.com/"),
    ("Allianz Travel", "Travel insurance", "US", "https://www.allianztravelinsurance.com/"),
    ("FM Global", "Property & casualty", "US", "https://www.fmglobal.com/"),
    ("Citizens Property Insurance", "National / state insurer", "US", "https://www.citizensfla.com/"),
    ("Suva", "Workers compensation", "CH", "https://www.suva.ch/"),
    ("Folksam", "Mutual / cooperative", "SE", "https://www.folksam.se/"),
    ("If Insurance", "Property & casualty", "FI", "https://www.if-insurance.com/"),
    ("Tryg", "Property & casualty", "DK", "https://www.tryg.com/"),
    ("Gjensidige", "Property & casualty", "NO", "https://www.gjensidige.com/"),
    ("Storebrand", "Pension / retirement", "NO", "https://www.storebrand.no/"),
    ("Varma", "Pension / retirement", "FI", "https://www.varma.fi/"),
    ("LähiTapiola", "Mutual / cooperative", "FI", "https://www.lahitapiola.fi/"),
    ("Mutua Madrileña", "Mutual / cooperative", "ES", "https://www.mutua.es/"),
    ("Techniker Krankenkasse", "Health insurance", "DE", "https://www.tk.de/"),
    ("Barmer", "Health insurance", "DE", "https://www.barmer.de/"),
    ("AOK", "Health insurance", "DE", "https://www.aok.de/"),
    ("Talanx HDI Global", "Property & casualty", "DE", "https://www.hdi.global/"),
    ("Mobiliar", "Mutual / cooperative", "CH", "https://www.mobiliar.ch/"),
    ("Income Insurance", "Life insurance", "SG", "https://www.income.com.sg/"),
    ("Great Eastern", "Life insurance", "SG", "https://www.greateasternlife.com/"),
    ("Prudential Singapore", "Life insurance", "SG", "https://www.prudential.com.sg/"),
    ("MSIG", "Property & casualty", "SG", "https://www.msig.com.sg/"),
    ("Tokio Marine Singapore", "Property & casualty", "SG", "https://www.tokiomarine.com.sg/"),
    ("Qatar Insurance", "Composite / multiline", "QA", "https://www.qic-group.com/"),
    ("Oman Insurance", "Composite / multiline", "AE", "https://www.omaninsurance.ae/"),
    ("ADNIC", "Composite / multiline", "AE", "https://www.adnic.ae/"),
    ("Tawuniya", "Takaful", "SA", "https://www.tawuniya.com.sa/"),
    ("Bupa Arabia", "Health insurance", "SA", "https://www.bupa.com.sa/"),
    ("Salama Takaful", "Takaful", "AE", "https://www.salama.ae/"),
    ("Discovery Limited", "Health insurance", "ZA", "https://www.discovery.co.za/"),
    ("Momentum Metropolitan", "Life insurance", "ZA", "https://www.momentummetropolitan.co.za/"),
    ("Outsurance", "Insurtech", "ZA", "https://www.outsurance.co.za/"),
    ("IAG NZ", "Property & casualty", "NZ", "https://www.iag.co.nz/"),
    ("Tower Insurance", "Property & casualty", "NZ", "https://www.tower.co.nz/"),
    ("AMP", "Life insurance", "AU", "https://www.amp.com.au/"),
    ("TAL", "Life insurance", "AU", "https://www.tal.com.au/"),
    ("Medibank", "Health insurance", "AU", "https://www.medibank.com.au/"),
    ("Bupa Australia", "Health insurance", "AU", "https://www.bupa.com.au/"),
    ("NIB", "Health insurance", "AU", "https://www.nib.com.au/"),
    ("HCF", "Health insurance", "AU", "https://www.hcf.com.au/"),
    ("BRADESCO Seguros", "Composite / multiline", "BR", "https://www.bradescoseguros.com.br/"),
    ("Porto Seguro", "Composite / multiline", "BR", "https://www.portoseguro.com.br/"),
    ("SulAmérica", "Health insurance", "BR", "https://www.sulamerica.com.br/"),
    ("GNP Seguros", "Composite / multiline", "MX", "https://www.gnp.com.mx/"),
    ("Qualitas", "Auto insurance", "MX", "https://www.qualitas.com.mx/"),
    ("Sura", "Composite / multiline", "CO", "https://www.sura.com/"),
    ("Rimac", "Composite / multiline", "PE", "https://www.rimac.com/"),
    ("IRB Brasil Re", "Reinsurance", "BR", "https://www.irbre.com/"),
    ("MS Amlin", "Marine / specialty", "GB", "https://www.msamlin.com/"),
    ("Lancashire", "Reinsurance", "GB", "https://www.lancashiregroup.com/"),
    ("Convex", "Reinsurance", "GB", "https://convexin.com/"),
    ("Kin Insurance", "Insurtech", "US", "https://www.kin.com/"),
    ("Branch Insurance", "Insurtech", "US", "https://www.ourbranch.com/"),
    ("Pie Insurance", "Insurtech", "US", "https://www.pieinsurance.com/"),
    ("Embroker", "Insurtech", "US", "https://www.embroker.com/"),
    ("Cowbell Cyber", "Insurtech", "US", "https://cowbell.insure/"),
    ("Ethos Life", "Insurtech", "US", "https://www.ethoslife.com/"),
    ("Ladder Life", "Insurtech", "US", "https://www.ladderlife.com/"),
    ("Bestow", "Insurtech", "US", "https://www.bestow.com/"),
    ("Hagerty", "Specialty / auto", "US", "https://www.hagerty.com/"),
    ("Pure Insurance", "Property & casualty", "US", "https://www.pureinsurance.com/"),
    ("Chubb Studio", "Property & casualty", "US", "https://www.chubb.com/us-en/"),
    ("Nationwide Pet", "Pet insurance", "US", "https://www.petinsurance.com/"),
    ("Figo Pet", "Pet insurance", "US", "https://figopetinsurance.com/"),
    ("Compare the Market", "Insurtech", "GB", "https://www.comparethemarket.com/"),
    ("Confused.com", "Insurtech", "GB", "https://www.confused.com/"),
    ("Check24 Versicherung", "Insurtech", "DE", "https://www.check24.de/versicherungen/"),
    ("Clark", "Insurtech", "DE", "https://www.clark.de/"),
    ("Ottonova", "Insurtech", "DE", "https://www.ottonova.de/"),
    ("Friday Insurance", "Insurtech", "DE", "https://www.friday.de/"),
    ("Neodigital", "Insurtech", "DE", "https://www.neodigital.de/"),
    ("Lovys", "Insurtech", "FR", "https://www.lovys.com/"),
    ("Leocare", "Insurtech", "FR", "https://www.leocare.eu/"),
    ("Shift Technology", "Insurtech", "FR", "https://www.shift-technology.com/"),
    ("Tractable", "Insurtech", "GB", "https://www.tractable.ai/"),
    ("FM Global Resilience", "Property & casualty", "US", "https://www.fm.com/"),
    ("Philadelphia Contributionship", "Mutual / cooperative", "US", "https://contributionship.com/"),
    ("New Jersey Manufacturers", "Mutual / cooperative", "US", "https://www.njm.com/"),
    ("Penn National Insurance", "Property & casualty", "US", "https://www.pennnationalinsurance.com/"),
    ("Westfield Insurance", "Mutual / cooperative", "US", "https://www.westfieldinsurance.com/"),
    ("Sentry Insurance", "Mutual / cooperative", "US", "https://www.sentry.com/"),
    ("Shelter Insurance", "Mutual / cooperative", "US", "https://www.shelterinsurance.com/"),
    ("Country Financial", "Mutual / cooperative", "US", "https://www.countryfinancial.com/"),
    ("Grange Insurance", "Property & casualty", "US", "https://www.grangeinsurance.com/"),
    ("Acuity Insurance", "Property & casualty", "US", "https://www.acuity.com/"),
    ("Arbella", "Property & casualty", "US", "https://www.arbella.com/"),
    ("Plymouth Rock", "Auto insurance", "US", "https://www.plymouthrock.com/"),
    ("The Hanover", "Property & casualty", "US", "https://www.hanover.com/"),
    ("RLI", "Specialty / surety", "US", "https://www.rlicorp.com/"),
    ("ProSight", "Marine / specialty", "US", "https://www.prosightspecialty.com/"),
    ("AmTrust", "Property & casualty", "US", "https://amtrustfinancial.com/"),
    ("National General", "Auto insurance", "US", "https://www.nationalgeneral.com/"),
    ("Palomar", "Property & casualty", "US", "https://plmr.com/"),
    ("Kinsale", "Marine / specialty", "US", "https://www.kinsaleins.com/"),
    ("Ryan Specialty", "Insurance broker", "US", "https://www.ryansg.com/"),
    ("Alliant Insurance", "Insurance broker", "US", "https://www.alliant.com/"),
    ("USI", "Insurance broker", "US", "https://www.usi.com/"),
    ("NFP", "Insurance broker", "US", "https://www.nfp.com/"),
    ("AssuredPartners", "Insurance broker", "US", "https://www.assuredpartners.com/"),
    ("Simply Business", "Insurtech", "GB", "https://www.simplybusiness.com/"),
    ("Coverwallet", "Insurtech", "US", "https://www.coverwallet.com/"),
    ("Thimble", "Insurtech", "US", "https://www.thimble.com/"),
    ("Vouch", "Insurtech", "US", "https://www.vouch.us/"),
    ("Steadily", "Insurtech", "US", "https://www.steadily.com/"),
    ("Openly", "Insurtech", "US", "https://www.openly.com/"),
    ("Clearcover", "Insurtech", "US", "https://www.clearcover.com/"),
    ("ManyPets", "Pet insurance", "GB", "https://www.manypets.com/"),
    ("Bought By Many", "Pet insurance", "GB", "https://boughtbymany.com/"),
    ("Embrace Pet Insurance", "Pet insurance", "US", "https://www.embracepetinsurance.com/"),
    ("Spot Pet", "Pet insurance", "US", "https://www.spotpetins.com/"),
    ("Allianz Direct", "Insurtech", "DE", "https://www.allianzdirect.de/"),
    ("CosmosDirekt", "Insurtech", "DE", "https://www.cosmosdirekt.de/"),
    ("Hannoversche", "Life insurance", "DE", "https://www.hannoversche.de/"),
    ("Nürnberger", "Life insurance", "DE", "https://www.nuernberger.de/"),
    ("Alte Leipziger", "Life insurance", "DE", "https://www.alte-leipziger.de/"),
    ("Barmenia", "Health insurance", "DE", "https://www.barmenia.de/"),
    ("DKV", "Health insurance", "DE", "https://www.dkv.com/"),
    ("Hallesche", "Health insurance", "DE", "https://www.hallesche.de/"),
    ("DAK-Gesundheit", "Health insurance", "DE", "https://www.dak.de/"),
    ("KKH", "Health insurance", "DE", "https://www.kkh.de/"),
    ("Matmut", "Mutual / cooperative", "FR", "https://www.matmut.fr/"),
    ("MMA", "Mutual / cooperative", "FR", "https://www.mma.fr/"),
    ("GMF", "Mutual / cooperative", "FR", "https://www.gmf.fr/"),
    ("MGEN", "Health insurance", "FR", "https://www.mgen.fr/"),
    ("AG2R La Mondiale", "Pension / retirement", "FR", "https://www.ag2rlamondiale.fr/"),
    ("Malakoff Humanis", "Pension / retirement", "FR", "https://www.malakoffhumanis.com/"),
    ("Generali Deutschland", "Composite / multiline", "DE", "https://www.generali.de/"),
    ("Württembergische", "Composite / multiline", "DE", "https://www.wuerttembergische.de/"),
    ("LVM Versicherung", "Mutual / cooperative", "DE", "https://www.lvm.de/"),
    ("VHV", "Property & casualty", "DE", "https://www.vhv.de/"),
    ("Provinzial", "Mutual / cooperative", "DE", "https://www.provinzial.de/"),
    ("Swiss Mobiliar", "Mutual / cooperative", "CH", "https://www.die-mobiliar.ch/"),
    ("Vaudoise", "Mutual / cooperative", "CH", "https://www.vaudoise.ch/"),
    ("Helvetia Schweiz", "Composite / multiline", "CH", "https://www.helvetia.ch/"),
    ("AXA Schweiz", "Composite / multiline", "CH", "https://www.axa.ch/"),
    ("CSS Versicherung", "Health insurance", "CH", "https://www.css.ch/"),
    ("Helsana", "Health insurance", "CH", "https://www.helsana.ch/"),
    ("Swica", "Health insurance", "CH", "https://www.swica.ch/"),
    ("Visana", "Health insurance", "CH", "https://www.visana.ch/"),
    ("KPT", "Health insurance", "CH", "https://www.kpt.ch/"),
    ("Concordia", "Health insurance", "CH", "https://www.concordia.ch/"),
]


def existing_hosts() -> set[str]:
    hosts: set[str] = set()
    for path in EXISTING:
        data = json.loads(path.read_text())
        for entry in data.get("entries", []):
            hosts.add(host_key(entry["url"]))
    return hosts


def source_rows() -> list[tuple[str, str, str, str]]:
    data = json.loads(SOURCE.read_text())
    rows: list[tuple[str, str, str, str]] = []
    for entry in data.get("entries", []):
        name = str(entry.get("name") or "").strip()
        url = str(entry.get("url") or "").strip()
        country = country_iso(str(entry.get("country") or ""), url)
        if not name or not url.startswith("https://"):
            continue
        rows.append((name, infer_group(name, url), country, url))
    return rows


def main() -> None:
    skip = existing_hosts()
    entries = []
    seen_ids: set[str] = set()
    seen_hosts: set[str] = set()
    for name, group, country, url in [*CURATED, *source_rows()]:
        key = host_key(url)
        ident = slug(name)
        if not ident or ident in seen_ids or key in seen_hosts or key in skip:
            continue
        if not url.startswith("https://"):
            continue
        host = key.split("/")[0]
        if host.endswith(".gov") or host.endswith(".edu"):
            continue
        seen_ids.add(ident)
        seen_hosts.add(key)
        entries.append(
            {
                "rank": len(entries) + 1,
                "id": ident,
                "name": name,
                "group": group,
                "country": country,
                "url": url,
            }
        )
        if len(entries) == 1000:
            break
    if len(entries) != 1000:
        raise SystemExit(f"expected 1000 unique entries, got {len(entries)}")
    catalog = {
        "id": "insurance-1000",
        "title": "1000 worldwide insurance, reinsurance, broker, health, and insurtech public homepages",
        "source": "Curated 2026 mix of life, P&C, health, reinsurance, brokers, mutuals, takaful, and insurtech. Majors first, then Wikidata/Wikipedia official websites. Excludes hosts already in automotive-oem-50, cross-industry-100, and engineering-manufacturing-1000.",
        "sourceUrl": "https://en.wikipedia.org/wiki/List_of_largest_insurance_companies",
        "year": 2026,
        "updated": "2026-08-18",
        "entries": entries,
    }
    OUT.write_text(json.dumps(catalog, indent=2) + "\n")
    groups = sorted({e["group"] for e in entries})
    print(f"wrote {OUT} ({len(entries)} entries, {len(groups)} groups)")
    print("groups:", ", ".join(groups))


if __name__ == "__main__":
    main()
